## This notebook:
- Include a comprehensive list of all the courses and their requirements distribution
- User enter a course, a requirement distribution, number of recommendation requested
- System gives the requested number of recommendation up to the maximum possible choices, based on the requirement distribution of that course

In [81]:
import pandas as pd

In [82]:
com_course_list = pd.read_csv('assets/com_course_list_w_requirements.csv')

In [83]:
cs_course_list = pd.read_csv('assets/Computer Science Program Major Requirements only.csv')

In [84]:
com_course_list['Requirement'] = 'LSA'
cs_course_list['Requirement'] = 'CS'

In [85]:
course_list = pd.concat([com_course_list, cs_course_list])

In [86]:
course_list

,Subject/Catalog,Course Title,Credits,Course List Description,Require,Requirement,Course ID/ Wildcard
0,ARTDE 129,First Year Writing in Art and Desitn,4.0,First-Year Writing Requirement,One,LSA,NaN
1,BIOLOG 197,Science Writing for Everyday Life,4.0,First-Year Writing Requirement,One,LSA,NaN
2,CLCI 121,First-year Seminar in Classical Civilization (...,4.0,First-Year Writing Requirement,One,LSA,NaN
3,COMPLI 122,Writing World Literatures,4.0,First-Year Writing Requirement,One,LSA,NaN
4,ENGLIS 124,Academic Writing and Literature,4.0,First-Year Writing Requirement,One,LSA,NaN
...,...,...,...,...,...,...,...
87,EECS 443,Senior Thesis,3.0,Computer Science Capstone,One,CS,45440
88,EECS 441,Mbl App Dev Entrprnr,4.0,Computer Science Capstone,One,CS,44359
89,EECS 473,Adv Embedded Sys,4.0,Computer Science Capstone,One,CS,45917
90,EECS 495,Software for Access,4.0,Computer Science Capstone,One,CS,48402
91,EECS 398,Special Topics,4.0,Computer Science Capstone,One,CS,12129

In [87]:
course_list.sample()

,Subject/Catalog,Course Title,Credits,Course List Description,Require,Requirement,Course ID/ Wildcard
3339,ASIA 368,How Different is Chinese?,3.0,Humanities,Two,LSA,NaN

In [88]:
valid_requirement_dist_options = course_list['Course List Description'].unique().tolist()

In [89]:
valid_requirement_dist_options

['First-Year Writing Requirement',
 'Upper-level Writing Requirement',
 'Full Quantitative Reasoning Credit (QR/1)',
 'Half Quantitative Reasoning Credit (QR/2)',
 'Race and Ethnicity',
 'Language Requirement',
 'Natural Science',
 'Social Science',
 'Humanities',
 'Mathematical and Symbolic Analysis',
 'Creative Expression',
 'Interdisciplinary',
 'Bachelor of Science Eligibility',
 'Community Based Learning',
 'Experiential',
 'Honors',
 'Independent',
 'Minicourse',
 'Sustainability',
 'CS-LSA major declaration Cal I',
 'CS-LSA major declaration Cal II',
 'CS-LSA major declaration ',
 'Core Probability',
 'Core CS',
 'Upper Level CS Technical Electives (ULCS) ',
 'Computer Science Capstone']

In [90]:
def recommend_course(courses_taken, course_type, num_to_recommend):
    
    df = course_list
    
    if courses_taken in course_list['Subject/Catalog'].tolist():
    
        type_of_course = df[df['Subject/Catalog'] == courses_taken]['Course List Description'].values[0]
        course_requirement = df[df['Subject/Catalog'] == courses_taken]['Require']
        course_requirement_of_type = df[df['Course List Description'] == course_type]['Require']

        # If the course entered belongs to the "One" list
        if course_requirement.any() == 'One':
            print(f'The requirement distribution of {courses_taken} is {type_of_course}.')
            print(f'You only need to take one course of the {type_of_course} requirement.')
            print(f'You have fully met the {type_of_course} requirement.')

        # If not
        elif course_requirement.any() != 'One':
            
            # If the type entered is not on the list
            if course_type not in course_list['Course List Description'].tolist():
                print('Requirement distribution not found')
            
            # If it does
            elif course_type in course_list['Course List Description'].tolist():

                # If the type of the course entered and the course type entered are not the same
                if type_of_course != course_type:

                    print('These courses are not of the same requirement')
                    print('----------------------')

                    print(f'The requirement distribution of {courses_taken} is {type_of_course}.')
                    print(f'Recommending courses of the same requirement with {courses_taken}:')
                    courses_of_same_type_entered = df[df['Course List Description'] == type_of_course]
                    courses_not_taken_entered = courses_of_same_type_entered[courses_of_same_type_entered['Subject/Catalog'] != courses_taken][['Subject/Catalog', 'Course Title']]

                    # If the number of course in list is longer than num_to_recommend
                    if len(courses_not_taken_entered) <  num_to_recommend:
                        courses_to_recommend_entered = courses_not_taken_entered[['Subject/Catalog', 'Course Title']]
                        print(f'Total number of recommendations: {len(courses_to_recommend_entered)}')

                    # If the number of course in list is shorter than num_to_recommend
                    else:
                        courses_to_recommend_entered = courses_not_taken_entered.sample(num_to_recommend)[['Subject/Catalog', 'Course Title']]
                        print(f'Total number of recommendations: {len(courses_to_recommend_entered)}')

                    print(courses_to_recommend_entered)
                    print('----------------------')

                    print(f'Recommending course of the {course_type} requirement:')
                    courses_of_same_type = df[df['Course List Description'] == course_type]
                    courses_not_taken = courses_of_same_type[courses_of_same_type['Subject/Catalog'] != courses_taken][['Subject/Catalog', 'Course Title']]

                    # If the number of course in list is longer than num_to_recommend
                    if len(courses_not_taken) <  num_to_recommend:
                        courses_to_recommend = courses_not_taken[['Subject/Catalog', 'Course Title']]
                        print(f'Total number of recommendations: {len(courses_to_recommend)}')

                    # If the number of course in list is shorter than num_to_recommend
                    else:
                        courses_to_recommend = courses_not_taken.sample(num_to_recommend)[['Subject/Catalog', 'Course Title']]
                        print(f'Total number of recommendations: {len(courses_to_recommend)}')

                    print(courses_to_recommend)

                ###########################################

            else:
                # If the type of the course entered and the course type entered are the same
                print(f'Course {courses_taken} is of {course_type} requirement.')
                print(f'Recommending course of the {course_type} requirement:')
                courses_of_same_type = df[df['Course List Description'] == course_type]
                courses_not_taken = courses_of_same_type[courses_of_same_type['Subject/Catalog'] != courses_taken][['Subject/Catalog', 'Course Title']]

                # If the number of course in list is longer than num_to_recommend
                if len(courses_not_taken) <  num_to_recommend:
                    courses_to_recommend = courses_not_taken[['Subject/Catalog', 'Course Title']]
                    print(f'Total number of recommendations: {len(courses_to_recommend)}')

                # If the number of course in list is shorter than num_to_recommend
                else:
                    courses_to_recommend = courses_not_taken.sample(num_to_recommend)[['Subject/Catalog', 'Course Title']]
                    print(f'Total number of recommendations: {len(courses_to_recommend)}')

                print(courses_to_recommend)
                
    else:
        print('Course not found')

In [91]:
recommend_course('EART 103', 'Social Science', 10)

These courses are not of the same requirement
----------------------
The requirement distribution of EART 103 is Natural Science.
Recommending courses of the same requirement with EART 103:
Total number of recommendations: 10
     Subject/Catalog                                       Course Title
2911      BIOLOG 144                                 Genetics & Society
2758        ASTR 127                                Naked Eye Astronomy
2879      PHYSIC 250       Fundamental Physics for the Life Sciences II
2925        EART 146                                       Plate Tecton
2937          EE 315                               Ecol&Evol Infect Dis
2782      BIOPHY 151         Physics for the Life Sciences Laboratory I
2871      PHYSIC 141                            Elementary Laboratory I
2790         CHE 130  General Chemistry: Macroscopic Investigations ...
2910      BIOLOG 110                                GC: Sustain Science
2837        EART 230  Natural and Environmental Hazards: Uncertainti...
----------------------
Recommending course of the Social Science requirement:
Total number of recommendations: 10
     Subject/Catalog                                Course Title
3172     ANTHRCU 319                                Lat-Amer Soc
3268          SO 220                               Politicl Econ
3018         ECO 370        Environmental and Resource Economics
3228        ISLA 241                           Amer&MidEast Wars
3015         ECO 108        Introductory Microeconomics Workshop
2961          AA 103           First Year Social Science Seminar
3249       POLSC 386                        Sports, Pol, Society
2981     ANTHRAR 284         Aztec, Maya, and Inca Civilizations
3098        PSYC 280           Introduction to Social Psychology
3110       RCSSC 275  Science, Technology, Medicine, and Society