<div>
<img src="Flowchart.jpg" width="1300"/>
</div>

In [1]:
import pandas as pd

### 1. Michigan Online Course Data with Course Descriptions

Current offerings of Michigan Online courses

In [2]:
m_online = pd.read_csv('assets/original/2021-10-19-MichiganOnline-courses.csv')

In [3]:
m_online

,name,description,experience_type
0,Accounting for Decision Making,"Through this course, you will start by address...",course
1,Achieving Health Equity in Healthcare,The third and the last course of the Addressin...,course
2,"Act on Climate: Steps to Individual, Community...",Are you concerned about climate change? Would ...,course
3,Additive Manufacturing,"This course, Additive Manufacturing, is the th...",course
4,Advanced Concepts in Time Value of Money (TVM),This course builds upon the fundamental concep...,course
...,...,...,...
516,Women & Incarceration (Seeking Justice: Conver...,This module examines the impacts of incarcerat...,course
517,Writing and Editing: Drafting,This third course in the “Good with Words: Wri...,course
518,Writing and Editing: Revising,This fourth and final course in the “Good with...,course
519,Writing and Editing: Structure and Organization,This second course in the Good with Words: Wri...,course
520,Writing and Editing: Word Choice and Word Order,This course will teach you how to use your wri...,course

### 2. Fall 2021/Winter 2022 Course Schedule Data

In [5]:
f_21 = pd.read_csv('assets/original/FA2021.csv')

In [6]:
f_21.head()

,Term,Session,Acad Group,Class Nbr,Subject,Catalog Nbr,Section,Course Title,Component,Codes,...,F,S,SU,Start Date,End Date,Time,Location,Instructor,Units,Unnamed: 23
0,Fall 2021,Regular Academic Session,Architecture & Urban Planning,35117,Architecture (ARCH),208,1,DESIGN FOUNDATIONS,SEM,P R,...,NaN,NaN,NaN,08/30/2021,12/10/2021,8-11AM,1360 A&AB,"Trandafirescu, Thut, Kang",3.00,NaN
1,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32571,Architecture (ARCH),216,1,Contested Spaces,LEC,S,...,NaN,NaN,NaN,08/30/2021,12/10/2021,1130-1PM,3600 SKB,Leon,4.00,NaN
2,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32573,Architecture (ARCH),216,2,Contested Spaces,DIS,P W,...,NaN,NaN,NaN,08/30/2021,12/10/2021,4-5PM,G026 TISCH,"Aquilina, Leon",4.00,NaN
3,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32575,Architecture (ARCH),216,3,Contested Spaces,DIS,P W,...,NaN,NaN,NaN,08/30/2021,12/10/2021,5-6PM,G026 TISCH,"Aquilina, Leon",4.00,NaN
4,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32577,Architecture (ARCH),216,4,Contested Spaces,DIS,P W,...,F,NaN,NaN,08/30/2021,12/10/2021,10-11AM,4154 LSA,"Ryu, Leon",4.00,NaN

In [7]:
w_22 = pd.read_csv('assets/original/WN2022.csv')

In [8]:
w_22.head()

,Term,Session,Acad Group,Class Nbr,Subject,Catalog Nbr,Section,Course Title,Component,Codes,...,F,S,SU,Start Date,End Date,Time,Location,Instructor,Units,Unnamed: 23
0,Winter 2022,First 7 Week Session,Architecture & Urban Planning,36999,Architecture (ARCH),251,1,SEEING,LAB,P W,...,NaN,NaN,NaN,01/05/2022,02/20/2022,830-1130AM,1360 A&AB,Harris,2.00,NaN
1,Winter 2022,Second 7 Week Session,Architecture & Urban Planning,37000,Architecture (ARCH),252,1,MEASURING,LAB,P W,...,NaN,NaN,NaN,03/07/2022,04/19/2022,830-1130AM,1360 A&AB,Harris,2.00,NaN
2,Winter 2022,First 7 Week Session,Architecture & Urban Planning,37001,Architecture (ARCH),253,1,SCALE,LAB,P,...,NaN,NaN,NaN,01/05/2022,02/20/2022,830-1130AM,B100 MLB,Gilpin,2.00,NaN
3,Winter 2022,Second 7 Week Session,Architecture & Urban Planning,37002,Architecture (ARCH),254,1,PROJECTION,LAB,P,...,NaN,NaN,NaN,03/07/2022,04/19/2022,830-1130AM,B100 MLB,Gilpin,2.00,NaN
4,Winter 2022,First 7 Week Session,Architecture & Urban Planning,37004,Architecture (ARCH),255,1,IMAGING,LAB,P,...,NaN,NaN,NaN,01/05/2022,02/20/2022,830-1130AM,B100 MLB,Halquist,2.00,NaN

### Course df with real-time enrollment

Real-time enrollment (seats remaining) is updated by the Office of the Registar via these links

In [9]:
f_21_open_link = 'https://ro.umich.edu/sites/default/files/timesched/pdf/FA2021_open.csv'
w_22_open_link = 'https://ro.umich.edu/sites/default/files/timesched/pdf/WN2022_open.csv'

In [10]:
f_21_open = pd.read_csv(f_21_open_link)
w_22_open = pd.read_csv(w_22_open_link)

In [11]:
f_21_open.head()

,Term,Session,Acad Group,Class Nbr,Subject,Catalog Nbr,Section,Course Title,Component,Codes,...,Start Date,End Date,Time,Location,Instructor,Total,Seats Remaining,Has WL,Units,Unnamed: 26
0,Fall 2021,Regular Academic Session,Architecture & Urban Planning,35117,Architecture (ARCH) Open Sections,208,1,DESIGN FOUNDATIONS,SEM,P R,...,08/30/2021,12/10/2021,8-11AM,1360 A&AB,"Trandafirescu, Thut, Kang",120,53,N,3.00,NaN
1,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32573,Architecture (ARCH) Open Sections,216,2,Contested Spaces,DIS,P,...,08/30/2021,12/10/2021,4-5PM,G026 TISCH,"Aquilina, Leon",24,2,Y,4.00,NaN
2,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32575,Architecture (ARCH) Open Sections,216,3,Contested Spaces,DIS,P,...,08/30/2021,12/10/2021,5-6PM,G026 TISCH,"Aquilina, Leon",24,2,Y,4.00,NaN
3,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32577,Architecture (ARCH) Open Sections,216,4,Contested Spaces,DIS,P,...,08/30/2021,12/10/2021,10-11AM,4154 LSA,"Ryu, Leon",24,1,Y,4.00,NaN
4,Fall 2021,Regular Academic Session,Architecture & Urban Planning,32579,Architecture (ARCH) Open Sections,216,5,Contested Spaces,DIS,P,...,08/30/2021,12/10/2021,11-12PM,5180B AH,"Ryu, Leon",24,1,Y,4.00,NaN

### 3. LSA Course Description

In [13]:
f_21_des = pd.read_csv('Scrape Course Description/f_21_des.csv')

In [14]:
f_21_des

,title,description,primary_instructor,subject,catalog_number,label_term,section,sub_title,credits,requirements_distribution,other,advisory_prerequisites,other_course_info,repeatability,consent
0,First Year Social Science Seminar,This course seeks to introduce students to eve...,"Stein,Howard",AAS,103,"Fall 2021,",Section 001,- Reading Africa: Critical Perspectives on Po...,3,SS,FYSem,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.,NaN
1,First Year Social Science Seminar,Blood diamonds. Resource curse. Land grabs. Th...,"Klein,Brian",AAS,103,"Fall 2021,",Section 002,- Reconsidering African Environments,3,SS,FYSem,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.,NaN
2,First Year Social Science Seminar,This course will examine the history of racial...,"Ashforth,Adam Philip",AAS,103,"Fall 2021,",Section 003,- South Africa: from Apartheid to Democracy,3,SS,FYSem,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.,NaN
3,First Year Humanities Seminar,This seminar introduces first-year students to...,"Zaborowska,Magdalena J",AAS,104,"Fall 2021,",Section 001,- Black Lives and Life Writing: How We Tell S...,3,HU,FYSem,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.,With permission of instructor.
4,First Year Humanities Seminar,This seminar introduces first-year students to...,"Deese,Adrian",AAS,104,"Fall 2021,",Section 003,- Black Atlantic Religion,3,HU,FYSem,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4478,Excelling in Upper-Level Writing,This course serves transfer and upper-division...,"Cicciarelli,Louis A",WRITING,350,"Fall 2021,",Section 001,NaN,1,NaN,NaN,Upper-level transfer students concurrently enr...,NaN,May be elected twice for credit.,NaN
4479,Advanced Rhetoric and Research,Communicating scientific information calls for...,"Brancho,James",WRITING,400,"Fall 2021,",Section 002,NaN,3,ULWR,NaN,Completion of the First-Year Writing Requirement.,NaN,May not be repeated for credit.,NaN
4480,Minor in Writing Capstone,This Minor in Writing Capstone Course gives yo...,"McDaniel,Raymond Clark",WRITING,420,"Fall 2021,",Section 001,NaN,3,ULWR,NaN,Completion of WRITING 220 and a majority of co...,NaN,May not be repeated for credit.,With permission of department.
4481,First Year Yiddish I,This is the first term of the two-year Yiddish...,"Luchina,Elena",YIDDISH,101,"Fall 2021,",Section 001,NaN,4,NaN,NaN,NaN,Graduate students elect JUDAIC 431 or YIDDISH ...,May not be repeated for credit.,NaN
4482,Second Year Yiddish I,This is the third term of the two-year Yiddish...,"Luchina,Elena",YIDDISH,201,"Fall 2021,",Section 001,NaN,4,NaN,NaN,JUDAIC/YIDDISH 102.,Graduate students elect JUDAIC 531 or YIDDISH ...,May not be repeated for credit.,NaN

In [15]:
w_22_des = pd.read_csv('Scrape Course Description/w_22_des.csv')

In [16]:
w_22_des

,title,description,primary_instructor,subject,catalog_number,label_term,section,sub_title,credits,requirements_distribution,other,consent,advisory_prerequisites,other_course_info,repeatability
0,First Year Social Science Seminar,This course seeks to introduce students to eve...,"Abdul Khabeer,Su'ad",AAS,103.0,"Winter 2022,",Section 004,- Black Women in the Archive,3,SS,FYSem,With permission of department.,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.
1,First Year Humanities Seminar,This seminar introduces first-year students to...,"Santamarina,Xiomara A",AAS,104.0,"Winter 2022,",Section 003,- Migrations in 20th Century Black Literature...,3,HU,FYSem,NaN,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.
2,First Year Humanities Seminar,This class explores the fascinating shift in B...,"Wells,Jonathan Daniel",AAS,104.0,"Winter 2022,",Section 004,- Nineteenth century Af Am History,3,HU,FYSem,NaN,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.
3,First Year Humanities Seminar,This seminar introduces first-year students to...,"Ekotto,Frieda",AAS,104.0,"Winter 2022,",Section 005,- Global Blackness,3,HU,FYSem,NaN,"Enrollment restricted to first-year students, ...",(Cross-Area Courses). May not be included in a...,May not be repeated for credit.
4,Elementary Swahili II: Language and Culture,This is a continuation of AAS 115. It is the s...,"Mwipopo,Marko",AAS,116.0,"Winter 2022,",Section 002,NaN,4,NaN,NaN,NaN,AAS 115.,NaN,May not be repeated for credit.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4663,Minor in Writing Capstone,This Minor in Writing Capstone Course gives yo...,"Hetzel, T",WRITING,420.0,"Winter 2022,",Section 001,NaN,3,ULWR,NaN,With permission of department.,Completion of WRITING 220 and a majority of co...,NaN,May not be repeated for credit.
4664,Minor in Writing Capstone,This Minor in Writing Capstone Course gives yo...,"McDaniel,Raymond Clark",WRITING,420.0,"Winter 2022,",Section 002,NaN,3,ULWR,NaN,With permission of department.,Completion of WRITING 220 and a majority of co...,NaN,May not be repeated for credit.
4665,Minor in Writing Capstone,This Minor in Writing Capstone Course gives yo...,"Babcock,Julie A",WRITING,420.0,"Winter 2022,",Section 003,NaN,3,ULWR,NaN,With permission of department.,Completion of WRITING 220 and a majority of co...,NaN,May not be repeated for credit.
4666,First Year Yiddish II,"This class is open to total beginners, as well...","Luchina,Elena",YIDDISH,102.0,"Winter 2022,",Section 001,NaN,4,NaN,NaN,NaN,JUDAIC/YIDDISH 101.,Graduate students elect JUDAIC 432 or YIDDISH ...,May not be repeated for credit.
4667,Second Year Yiddish II,This year we will continue the course of study...,"Luchina,Elena",YIDDISH,202.0,"Winter 2022,",Section 001,NaN,4,NaN,Lang Req,NaN,JUDAIC/YIDDISH 201.,Graduate students elect JUDAIC 532 or YIDDISH ...,May not be repeated for credit.

### 4. Merge Course Schedule and Descriptions

In [17]:
def merge_df(open_df, des_df):
    
    # Create new column of course subject i.e. AAS 103 in open_df
    subject = open_df['Subject']
    open_df['subject'] = [s[s.find("(")+1:s.find(")")] for s in subject]
    open_df['course'] = open_df['subject'] + open_df['Catalog Nbr']
    open_df.sort_values(by=['course'], inplace=True)
    
    # Create new column of course subject i.e. AAS 103 in des_df
    des_df['Catalog Nbr'] = des_df['catalog_number'].dropna().astype(int).astype(str)
    des_df['course'] = des_df['subject'] + ' ' + des_df['Catalog Nbr']
    
    # Merge these dfs
    df = open_df.merge(des_df, on=['course'], how='left', copy=False)
    
    cols = ['Class Nbr', 'course', 'Term', 'Session', 'Acad Group', 'Subject', 'Course Title', 'description', 'Component', 'Time', 'Location', 
        'Instructor', 'Total', 'Seats Remaining', 'Has WL', 'Units', 'sub_title', 'credits', 'requirements_distribution', 'other', 'consent', 
        'advisory_prerequisites', 'other_course_info', 'repeatability']
    
    df = df[cols]
    
    return df

In [18]:
w_22_merge = merge_df(w_22_open, w_22_des)

In [19]:
f_21_merge = merge_df(f_21_open, f_21_des)

In [21]:
f_21_merge.to_csv('assets/f_21_merge.csv', index=False)

In [22]:
w_22_merge.to_csv('assets/w_22_merge.csv', index=False)

In [ ]:
w_22_merge['description'][100]

In [ ]:
w_22_merge.columns

In [ ]:
f_21_merge[['Subject', 'Course Title', 'course', 'Acad Group', 'requirements_distribution']]